### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by tholu** [alwex/php-casperjs#15]
Can you tag releases, so in composer.json I can use a specific version instead of ```dev-master```?

**Comment by fguery** [comment]
+1 :)

**Comment by alwex** [comment]
Tag is ok now, let me now if it is ok for you

**Comment by tholu** [comment]
The tag does not appear on packagist yet, can you take a look? https://packagist.org/packages/phpcasperjs/phpcasperjs

**Comment by alwex** [comment]
I have manually updated the package on packagist, it seems to be ok now.
